name: Deploy Pages

on:
  push:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn set version berry && yarn --immutable

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
